# Numpy Basics

### Importing packages

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Array 1 

In [98]:
a = np.array([[10,1,2], [1,6,0]])

### Array 2

In [99]:
b = np.array([[1,2,3], [4,5,6]])

.

### Functions ---

### 1. min()

In [4]:
a.min()

0

In [107]:
store = a[0][0]

for i in a:
    for j in i:
        if j < store:
            store = j
store

0

### 2. max()

In [7]:
a.max()

10

In [109]:
store = a[0][0]

for i in a:
    for j in i:
        if j>store:
            store =j 
store            

10

### 3. mean()

In [9]:
a.mean()

3.3333333333333335

In [113]:
sum_, count = 0.0, 0

for i in a:
    for j in i:
        sum_ +=j
        count +=1  

sum_/count

3.3333333333333335

### 4. argmin()

In [104]:
np.argmin(a, axis = 1)

array([1, 2])

In [114]:
# Calculating for: argmin(a, axis = 1)
min_list = []

for i in a:
    store = i[0]
    index = 0
    
    for j in i:
        if j < store:
            store = j
            min_index = index
        index +=1
    
    min_list.append(min_index)
min_list

[1, 2]

### 5. argmax()

In [20]:
np.argmax(a,axis=1)

array([0, 1])

In [115]:
max_list = []

for i in a:
    store = i[0]
    index = 0
    
    for j in i:
        if j >= store:
            store = j
            max_index = index
        index +=1
    max_list.append(max_index)
max_list

[0, 1]

### 6. linalg.solve

In [126]:
A = np.array([[1,2],[3,4]]) 
B = np.array([[10],[20]])

np.linalg.solve(A,B)

array([[ 0.],
       [ 5.]])

### 7. flatten


In [117]:
a.flatten()

array([10,  1,  2,  1,  6,  0])

In [124]:
flat = []

for i in a:
    for j in i:
        flat.append(j)   
flat

[10, 1, 2, 1, 6, 0]

### 8. ravel()

In [121]:
a.ravel()

array([10,  1,  2,  1,  6,  0])

In [127]:
ravelled = []

for i in a:
    for j in i:
        ravelled.append(j)
ravelled

[10, 1, 2, 1, 6, 0]

### 9. dot Product

In [72]:
a

array([[10,  1,  2],
       [ 1,  6,  0]])

In [94]:
# Rows and columns:
len(a), len(a[0])

(2, 3)

In [87]:
dot_p = [[x for x in range(len(a[0]))] for x in range(len(a))]

for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            dot_p[i][j] = a[i][k] * b[k][j]
dot_p        

[[4, 5, 6], [24, 30, 36]]

### 10. * for 

In [95]:
a

array([[10,  1,  2],
       [ 1,  6,  0]])

In [129]:
np.multiply(a,b)

array([[10,  2,  6],
       [ 4, 30,  0]])

In [133]:
result_array = ([[0,0,0],[0,0,0]])
a_rows,a_cols = a.shape

for i in range(a_rows):
    for j in range(a_cols):
        result_array[i][j] = a[i][j]*b[i][j]

result_array

[[10, 2, 6], [4, 30, 0]]

### 11. Reshape

In [154]:
k = np.arange(4)
k

array([0, 1, 2, 3])

In [155]:
k.reshape(2,2)

array([[0, 1],
       [2, 3]])

In [153]:
reshaped = np.array([[0,0],[0,0]])
reshaped_rows,reshaped_cols = b.shape 

s = 0
for i in range(b_rows):
    for j in range(b_cols):
        reshaped[i][j] = a[s]
        s += 1
        
reshaped

array([[0, 1],
       [2, 3]])

### 12. identity / eye

In [167]:
i_m = np.identity(3)
i_m

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [166]:
b = np.empty(i_m.size)


s = 0
i_m_rows, i_m_cols = i_m.shape
for i in range(i_m_rows):
    for j in range(i_m_cols):
        if i == j:
            b[s] = 1
            s += 1
        else:
            b[s] = 0
            s += 1
print("without using inbuilt api diagonal array is\n",b.reshape(3,3))

without using inbuilt api diagonal array is
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### 13. sum()

In [168]:
a.sum()

6

In [169]:
sum = 0 

for i in range(a.size):
    sum += a.item(i)
sum    

6

### 14. diag()

In [170]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [171]:
np.diag(a)

array([0, 4, 8])

In [174]:
b = np.empty(3)

s = 0
a_rows, a_cols = a.shape
for i in range(a_rows):
    for j in range(a_cols):
        if i == j:
            b[s] = a[i,j]
            s += 1
b 

array([ 0.,  4.,  8.])

### 15. tril / triu

In [177]:
np.tril(a)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [178]:
b = np.empty(9)
s = 0
a_rows, a_cols = a.shape
for i in range(a_rows):
    for j in range(a_cols):
        if i < j:
            b[s] = 0
            s += 1
        else:
            b[s] = a[i,j]
            s += 1
print("without using inbuilt api\n",b.reshape(3,3))            

without using inbuilt api
 [[ 0.  0.  0.]
 [ 3.  4.  0.]
 [ 6.  7.  8.]]
