# Numpy Basics

In [1]:
import numpy as np

In [15]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [20]:
np.linspace(0,10, 5)

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [27]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a.shape

(3, 3)

In [44]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [30]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a.max(axis=0)

array([7, 8, 9])

In [34]:
a.min(axis = 1)

array([1, 4, 7])

In [37]:
x = np.random.random((3,2))
x

array([[ 0.09276559,  0.86033706],
       [ 0.34852178,  0.36195233],
       [ 0.08221019,  0.24840283]])

array([[8, 8, 8],
       [8, 8, 8]])